# Generated by Django 3.2.13 on 2022-08-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_doctor', '0003_alter_appoinment_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='specification',
            field=models.CharField(max_length=225),
        ),
    ]
